server:
  port: 8081

spring:
  datasource:
    url: "${DATABASE_URL:jdbc:postgresql://ep-red-moon-akd52v7p-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require}"
    username: "${DATABASE_USERNAME:neondb_owner}"
    password: "${DATABASE_PASSWORD:npg_2sR7BqdkVbjp}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
